### PR TITLE
Fix location info in example certificate

### PR DESCRIPTION
**Pull request by geky**
This was clearly just a typo

### CODE REVIEW

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: 038e6d3745bda0bf80b8053b0dbae4e22b17d59e
* Result: FAILED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=4c6635bf-d81f-4cc0-abcb-1e14ca4cb31c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by dominic-mulligan-arm** [comment]
I like your style.

**Review by dominic-mulligan-arm — APPROVED** [review]

**Review by dreemkiller — APPROVED** [review]

**Comment by dominic-mulligan-arm** [comment]
Build is broken due to another transitive dependency updating (`value-bag`).  I think I am going to prioritise #60.

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: b50fb60cbc8acc9c62dd15dd80f9f55f917c6afe
* Result: SUCCEEDED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=7f260985-042c-451a-aabb-5b8e4ec2c584%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by dominic-mulligan-arm** [comment]
+1+1=+1

**Pull request merged**
