### PR TITLE
Update actix crates

### PR DESCRIPTION
**Pull request by mathias-arm**
Update the `actix-web` (and related) crate to latest stable version. With current version `cargo audit` complains about vulnerabilities.

### CODE REVIEW

**Review by dominic-mulligan-arm — DISMISSED** [review]

**Comment by dominic-mulligan-arm** [comment]
lgtm

**Review by gbryant-arm — APPROVED** [review]
LGTM.
cargo complains about `actix-rt = "1.0.0"` but not about `actix-rt = "1"`? Weird

**Comment by mathias-arm** [comment]
Should I update the pull request to include full versions?

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: e2fd78587156ff5d5f97961e1c2247df50a83b4b
* Result: SUCCEEDED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=fd1bc187-b653-4fcd-b9f2-f2711b787541%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: 409884ff00ee4ff87f9ef39848a03b6202ca4b5d
* Result: SUCCEEDED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=388a8d2e-b276-4eca-a5d2-d7f6ef6ab147%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by dominic-mulligan-arm — APPROVED** [review]

**Comment by dominic-mulligan-arm** [comment]
+1 reached, merging.

**Pull request merged**
