### PR TITLE
veracruz-utils/src/csr.rs: Generate certificate valid till 2031-02-01.

### PR DESCRIPTION
**Pull request by egrimley-arm**

### CODE REVIEW

**Comment by geky** [comment]
Judging from the code comments, it looks like this is just a temporary solution until the root enclaves are removed.

Pushing back the date is probably fine, but maybe we should only push it back a year? With the assertion that that if we haven't fixed this next year we should replace it with something that generates certs relative to the current date?

**Comment by egrimley-arm** [comment]
You think CI breaking in an obscure fashion is a good way to set ourselves a reminder to update the code? I would have thought that an issue database or a calendar entry would be a better way of doing that!

**Comment by egrimley-arm** [comment]
So as not to lose sight of the checks running on this commit, I've also created a slightly modified PR #286.

**Comment by dominic-mulligan-arm** [comment]
Is this a duplicate of #286?

**Comment by egrimley-arm** [comment]
> Is this a duplicate of #286?

Yes! Closing ...

**Pull request closed without merging**
