### PR TITLE
Move Rust-specific code into dedicated directory in `sdk/` to make way for C support

### PR DESCRIPTION
**Pull request by dominic-mulligan-arm**
Moved around various directories under `sdk` to make way for eventual C support.  This is laying the groundwork for #8.

### CODE REVIEW

**Comment by dominic-mulligan-arm** [comment]
(This build should still fail, but hopefully now we get an automated comment pointing us to some public build logs.)

**Comment by dominic-mulligan-arm** [comment]
(Another failing build triggered to test the CI commenting bot.)

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: 472e1653fddf20458cfa892747872f88d3413c56
* Result: FAILED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=b36bd227-c026-48df-9a8c-77a5e4a48d21%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: a419e028aceb277466da97d0c3597fbe859c8149
* Result: FAILED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=21333ef2-be1c-4d20-9884-c66b1ec257fc%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by dominic-mulligan-arm** [comment]
Closing this in favour of #44.  Submodule changes have made this a mess.

**Pull request closed without merging**
