### PR TITLE
Remove unused duplicates: host.nix realm.nix sdk-and-test-collateral.nix

### PR DESCRIPTION
**Pull request by egrimley-arm**
There remain some duplicates where both copies seem to be used:
```
config.nix
default.nix
instance.nix
targets.nix
```

This will be tidied up at some point.

### CODE REVIEW

**Comment by egrimley-arm** [comment]
Another `error: writing to file: No space left on device`.

**Comment by egrimley-arm** [comment]
One of the deleted files is under `workspaces`, though.

**Comment by mathias-arm** [comment]
I don't see an issue with removing the unused duplicates. The `FIXME` changes seem superfluous as we are gearing towards removing the non-workspace build system, I would prefer removing the files in question from `icecap/` and leave untouched the ones in `workspace/`.

**Comment by egrimley-arm** [comment]
I think I've worked out how to remove those files from `icecap/`. I hope that a new version of this PR will arrive soon.

**Comment by egrimley-arm** [comment]
This is replaced by #354.

**Pull request closed without merging**
