### PR TITLE
Bitflags fix

### PR DESCRIPTION
**Pull request by dreemkiller**
in `sdk/data-generators/string-generator`, a direct dependency was pulling in a new version of `bitflags` (1.3.2) that was incompatible with our `rustc`. I have pinned it to 1.2.1, which works with our `rustc` version.

### CODE REVIEW

**Comment by ShaleXIONG** [comment]
Is it overlap with #192  and it seems to contain some change from another pull request?

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: dcdf1fc89557498e070da97ec99ff617599c6184
* Result: FAILED
* [Build Logs](https://01evtei465.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=64bbfabe-1764-4904-822d-2c0f16c63d9b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by dreemkiller** [comment]
Dang, I used the wrong base. Gimme a sec.

**Comment by dominic-mulligan-arm** [comment]
Is this still relevant, @dreemkiller?

**Pull request closed without merging**
