### PR TITLE
icecap: Bump IceCap source

### PR DESCRIPTION
**Pull request by egrimley-arm**
This is an updated version of https://github.com/veracruz-project/veracruz/pull/338

### CODE REVIEW

**Comment by mathias-arm** [comment]
Can you cherry-pick the CI changes from #329 to test workspaces?

**Comment by egrimley-arm** [comment]
> Can you cherry-pick the CI changes from #329 to test workspaces?

See #343, but CI failed because of `No space left on device`.

**Comment by mathias-arm** [comment]
This PR seems to combine #338 and #346. Given the upcoming changes to `icecap` I don't think we need to merge the #338 part, and the #346 part should be handled in that PR.

**Comment by egrimley-arm** [comment]
> This PR seems to combine #338 and #346. Given the upcoming changes to `icecap` I don't think we need to merge the #338 part, and the #346 part should be handled in that PR.

Yes, it's rebased onto #346, which I think is the highest priority for merging.

If we don't merge #338, then it will be deleted. I thought it might be useful to have it in the history.

**Comment by mathias-arm** [comment]
Let's focus on #346 and when it is merged we can consider whether keeping the changes inherited from #338 are worth preserving given the conflicts they will create in other branches.

**Comment by egrimley-arm** [comment]
This currently does not work: `make icecap` fails. The `bindgen` output is somehow incompatible with the changed environment. It worked quite recently. Perhaps the change from `bindgen` `0.57` to `0.59` broke it somehow?

**Comment by egrimley-arm** [comment]
Changing `bindgen` from `0.59.2` to `0.57` seems to fix the problem with `make icecap`.

**Comment by dominic-mulligan-arm** [comment]
Given #351 has been merged, is this ready for merging now, pending successful review?

**Review by geky — DISMISSED** [review]
This looks good to me, assuming it's working

**Comment by dominic-mulligan-arm** [comment]
Unfortunately it needs rebasing onto `main` before it can be merged.

**Comment by egrimley-arm** [comment]
I have rebased and tested on IceCap with:
```
cd workspaces
make icecap
make -C icecap-host run-tests
```

**Review by dominic-mulligan-arm — APPROVED** [review]

**Pull request merged**
