### PR TITLE
Undo changes for Veracruz in QCBOR and t_cose.

### PR DESCRIPTION
**Pull request by egrimley-arm**

### CODE REVIEW

**Comment by dominic-mulligan-arm** [comment]
What's the context behind this change?

**Comment by egrimley-arm** [comment]
> What's the context behind this change?

30a948627f4223ca1fcb3d9c9313131db2bc7e0b makes `psa-attestation`'s Makefile build a single static library, that includes `QCBOR` and `t_cose`. That makes the local changes we made in the makefiles for `QCBOR` and `t_cose` redundant, so I've undone those changes to make our versions of those submodules closer to upstream.

(In both cases there are plenty of newer commits upstream that someone might want to review at some point, but presumably there's no urgency for that.)

**Comment by dominic-mulligan-arm** [comment]
Ah OK, thanks for explaining.  I will approve, though let's wait for @dreemkiller's approval before merging.

**Review by dominic-mulligan-arm — APPROVED** [review]

**Review by mathias-arm — APPROVED** [review]

**Comment by dominic-mulligan-arm** [comment]
+1+1 = +1 reached, merging.

**Pull request merged**
