### PR TITLE
Rename Durango to VeracruzClient

### PR DESCRIPTION
**Pull request by gbryant-arm**
This PR aims at renaming Durango to VeracruzClient (modules, structures, error messages, doc).

Ready for review

### CODE REVIEW

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: 590c828ea2236019edc607f71082b537490b5d06
* Result: FAILED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=c3f5c7e5-9636-4055-9d95-52ee9506e253%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by dominic-mulligan-arm** [comment]
@gbryant-arm, please include a more descriptive summary of what this change does.  Any comment like "ready for review" should be added in a comment in the thread of updates below the main description.  Thanks!

**Comment by gbryant-arm** [comment]
Not sure how we should refer to Durango in the documentation: Veracruz client? VeracruzClient? client?

**Comment by dominic-mulligan-arm** [comment]
In documentation I think we should fix on using idiomatic English, so "the Veracruz client software" or something like that.  The first time it is mentioned you could clarify that this is in the "veracruz-client" directory in the repository.

**Comment by gbryant-arm** [comment]
Do you consider comments as documentation?

**Comment by dominic-mulligan-arm** [comment]
I don't think we should be as prescriptive in comments as we are in dedicated documentation files/the Wiki.  I think inline and Rustdoc-style comments can use either the idiomatic English phrasing or the Rust component names without confusion.

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: e4215716c2edfc7221a6abb236f9baaa4fca6ed7
* Result: FAILED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=0572c056-c455-41e5-9854-cd009431d825%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: 6cd0b0503d5794ebbf9ba6cbb836c3169f25f9fd
* Result: FAILED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=cb472b95-b3a4-4aa0-99cf-d5b2eae26975%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: 6f6a1b93c1a773af3cdc1381239c79b95f76334b
* Result: FAILED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=dcf1e19b-bf20-4e70-8f99-c66be1d8df6d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: 6527a5c2ea284434dc4a93e47ea1b96407724b97
* Result: SUCCEEDED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=af540a6c-4be2-4871-a35c-ba23e26d5ae6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by dominic-mulligan-arm — APPROVED** [review]

**Comment by dominic-mulligan-arm** [comment]
+1 reached, merging.

**Pull request merged**
