### PR TITLE
Reorganization of content of veracruz-utils to make way for Linux support

### PR DESCRIPTION
**Pull request by dominic-mulligan-arm**
This is to make way for Linux support.  Veracruz utils has become a bit of an unruly mess, with lots of material that is not well organized, and some large monolithic files containing all sorts of poorly-related material.

1. Move platform-specific material under a dedicated `platform` module hierarchy, with submodules for each platform (e.g. `tz`) and in-time related groups of platforms (e.g. `vm` for VM-related platforms like Nitro and Linux).
2. Split some large monlothic files up in `policy.rs` into smaller, more focussed source files containing closely-related material.
3. Introduce a new module, `io`, dedicated to material related-to vsockets and rawfd types.  Some material has been moved out of Nitro-related files as a result.
4. Made some small generalizations and quality-of-life improvements to existing material, e.g. policy timepoints are now checked as they are constructed to make sure that month, days, hours, minutes look reasonable.  Previously a TODO.  Preferred use of Rust stdlib `TryFrom` crate instead of ad-hoc conversion functions from `u32` in various opcode files, and so on.
5. Added new Rustdoc comments throughout.
6. Stopped re-exporting all modules from `veracruz-utils`.

### CODE REVIEW

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: 6fadfe325f509addbfff4a23313cbf0008236dec
* Result: FAILED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=4b21c7a1-c7a1-45bf-956b-e0f658e666fa%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: 88ccadbf28115737001a9176e96e3d625596fcdd
* Result: SUCCEEDED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=76e4b9e4-71bc-4b7c-b84f-51463e2e22e1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: 99d96980e297df34771bac2541e858a68745392e
* Result: SUCCEEDED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=8e395991-2f44-4d2b-b650-0e95b6effba1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: 89c96fed07926f79303fce508efe42e7301284df
* Result: SUCCEEDED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=a91fb859-bf2c-464c-9d6b-e83549abc7d3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: c9a68f0a99b0b98c8d9e8607cb6c9d8bce920b30
* Result: SUCCEEDED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=3375a85a-f248-48c7-bd22-ccdc8bafef02%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by ShaleXIONG — APPROVED** [review]

**Comment by dominic-mulligan-arm** [comment]
+1 reached, merging.

**Pull request merged**
