### PR TITLE
pipline example added

### PR DESCRIPTION
**Pull request by AryanGodara**
```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```
This example is with respect to the 2nd point in #377 issue.

The example consists of two programs:

1. binary-to-ascii: converts ascii input to binary output
2. longest-subarray: reads the binary output to find the longest subarrays: 1. alternating(0101) 2. zeroes(000) 3. ones(111)

I know there can be many errors in this, and I will work on each of them. This is to start the process of learning this type of examples.

### CODE REVIEW

**Comment by AryanGodara** [comment]
I will fix the first commit, it seems that it isn't verified somehow, and I've also added Cargo.lock files. Really sorry for this!!

**Comment by dominic-mulligan-arm** [comment]
@AryanGodara what is the interest in finding longest subarrays in the sense described above?  Is there a concrete use-case for that?

**Review by ShaleXIONG — APPROVED** [review]

**Comment by AryanGodara** [comment]
> @AryanGodara what is the interest in finding longest subarrays in the sense described above? Is there a concrete use-case for that?

There isn't exactly a use case for this, it's just that this is a way to combine the output of the huffman_encoding program (which gives a long string of 0s and 1s), and performing operations on it, to obtain a new result.

This is with reference to Issue #377 Add more examples.
```
Pipeline examples. This will be similar to the Linux pipeline command1 | command2 | command3. In the Veracruz content, the first program, prog_1, writes the result to a file, e.g., result_1.dat and the second program prog_2 reads the previous result in result_1.dat and then writes the new result to, e.g., result_2.dat and so on. In this setting, the WASM programs may be compiled from different source languages such as a combination of Rust and C.
```

I will later make changes to this same PR, as I learn more.
Like adding one more program. Or using both C and Rust.

**Comment by AryanGodara** [comment]
But there are a few issues with this code, some corner cases, and unnecessary comments. Which I'm just about to fix!

**Comment by dominic-mulligan-arm** [comment]
> > @AryanGodara what is the interest in finding longest subarrays in the sense described above? Is there a concrete use-case for that?
> 
> There isn't exactly a use case for this, it's just that this is a way to combine the output of the huffman_encoding program (which gives a long string of 0s and 1s), and performing operations on it, to obtain a new result.
> 
> This is with reference to Issue #377 Add more examples.
> 
> ```
> Pipeline examples. This will be similar to the Linux pipeline command1 | command2 | command3. In the Veracruz content, the first program, prog_1, writes the result to a file, e.g., result_1.dat and the second program prog_2 reads the previous result in result_1.dat and then writes the new result to, e.g., result_2.dat and so on. In this setting, the WASM programs may be compiled from different source languages such as a combination of Rust and C.
> ```
> 
> I will later make changes to this same PR, as I learn more. Like adding one more program. Or using both C and Rust.

Ok, but I think we should try to ensure that our examples correspond to plausible potential use-cases for Veracruz and are not confected.  Here's a potentially more interesting example of where pipelines may be used in Veracruz, for example:

1. The first program, `anonymise`, takes as input a CSV file containing data to be used for machine learning, and anonymises the data that it contains, maybe using differential privacy or k-anonymity.
2. The second program, `learn`, applies some machine learning algorithm to the anonymised data.

**Comment by AryanGodara** [comment]
> 

Wow, this is advanced for me!😅
Can I take some time for this one, like 1-2 weeks?
I have almost 0 experience with Machine learning, and I'll most probably have to use rust to make it work with wasm.

This will be a challenge and a great learning opportunity! I will get started with it in a day or two (I'm about to dual boot ubuntu since Windows is not at all reliable when working with Veracruz, haha). So it'll take some time to set it up, get familiar with it, and set up my workspace again!

Thank you @dominic-mulligan-arm for giving such an awesome suggestion!!

**Comment by dominic-mulligan-arm** [comment]
> Wow, this is advanced for me!😅 Can I take some time for this one, like 2-3 weeks? (I also have a few labs in college this month😅) I have almost 0 experience with Machine learning, and I'll most probably have to use rust to make it work with wasm.
> 
> This will be a challenge and a great learning opportunity! I will get started with it in a day or two (I'm about to dual boot ubuntu since Windows is not at all reliable when working with Veracruz, haha). So it'll take some time to set it up, get familiar with it, and set up my workspace again!
> 
> Thank you @dominic-mulligan-arm for giving such an awesome suggestion!!

@AryanGodara I don't think you need to develop the ML algorithm yourself, you can use a library like `rusty_machine` (see e.g., the `linear-regression` example in `rust-examples`).

**Comment by dominic-mulligan-arm** [comment]
(Though I will close this PR as I don't believe it's a useful example for us to include.)

**Comment by AryanGodara** [comment]
> 

Ohh, that's a relief

**Comment by AryanGodara** [comment]
> (Though I will close this PR as I don't believe it's a useful example for us to include.)

Yes, I understand.
I'll work on the more relevant topic that you suggested. Thank you for helping me out!!

**Pull request closed without merging**
