### PR TITLE
Normalized all Cargo/Xargo.toml files

### PR DESCRIPTION
**Pull request by dominic-mulligan-arm**
Folliowing a comment by @mathias-arm about the state of the project's `Cargo.toml` files, I've applied a formatting tool to our `Cargo.toml` and `Xargo.toml` files to normalise them.

### CODE REVIEW

**Comment by mathias-arm** [comment]
I think the only part I like is the "features" normalization, but even then they are not sorted and some comments were removed.

I am not fond of:
- the change from double quotes to single quotes.
- the dependencies are not sorted neither in the `[dependencies]` section, nor the `[dependencies.*]` sections
- putting dependencies into separate section, I'd prefer keeping them on one line but having that line be consistently formatted.

**Comment by dominic-mulligan-arm** [comment]
I've demoted this to a draft after a conversation with @mathias-arm and us looking for alternatives to `toml-fmt`, which is the tool that I used for formatting.

**Comment by nspin** [comment]
The implementation [1] of `toml-fmt` doesn't seem particularly tailed for Cargo manifests.

I recently had to solve a similar problem in IceCap. After a quick survey, the best solution I could come up with was rolling my own little Python script that did the ordering and choosing of what dictionaries to inline [2].

[1] https://github.com/segeljakt/toml-fmt/blob/master/src/main.rs
[2] https://gitlab.com/arm-research/security/icecap/icecap/-/blob/main/nix/scope/crates/generate/append-to-manifest.py

**Comment by mathias-arm** [comment]
There are a lot of tools that do some part of it. `taplo` is close, but is tripped up by comments in dependencies. `cargo-sort` is a nice complement (`cargo-sort` only does dependencies, `taplo` also sorts things like `package` and `features` sections).

```
$ cargo-sort <path/to/Cargo.toml>
$ taplo fmt -o align_entries=false,reorder_keys=true <path/to/Cargo.toml>
```

**Comment by dominic-mulligan-arm** [comment]
How about now?  This was formatted using @mathias-arm's suggestion of a combination of `cargo-sort` and `taplo` above:

```
for F in `ls */Xargo.toml`; do cargo-sort $F && taplo fmt -o align_entries=false,reorder_keys=true $F; done;
```

If everybody is happy with this formatting then I can also promote this into a Git pre-commit check via an appropriate hook.

**Comment by mathias-arm** [comment]
That's a lot better.  The only thing that looks out of place are those:

```
serde = { git = "https://github.com/veracruz-project/serde.git", features = [
  "derive",
], branch = "veracruz" }
```

**Comment by mathias-arm** [comment]
@dominic-mulligan-arm, can you try with adding `column_width=120` option to `taplo` call?

**Comment by dominic-mulligan-arm** [comment]
@mathias-arm, yeah, I'll try that.

**Comment by dominic-mulligan-arm** [comment]
OK, done!

**Review by mathias-arm — APPROVED** [review]
That's good!

**Review by ShaleXIONG — APPROVED** [review]
Is there tool to do that? or it relies on us to maintain the normal form?

**Review by geky — APPROVED** [review]
Looks good to me, though I try to not have an opinion on style.

Since this is a rerunnable script I do think we should try to merge as many PRs before to save on rebasing headaches.

**Comment by mathias-arm** [comment]
> Is there tool to do that? or it relies on us to maintain the normal form?

The tools used are `cargo-sort` and `taplo` (`cargo-sort <file>` and `taplo fmt -o align_entries=false,reorder_keys=true, column_width=120 <file>`).

**Comment by mathias-arm** [comment]
> Since this is a rerunnable script I do think we should try to merge as many PRs before to save on rebasing headaches.

Since this is an automated process you can also run it at the end of the branch and squash your branch (not sure if you could rebuild the whole branch and keep distinct commits). This way, there should not be any rebase headaches. Same thing should be possible with `rustfmt` changes.

**Comment by mathias-arm** [comment]
Adding `array_auto_collapse=false` to taplo command line prevents it from putting smaller arrays into one line.
`taplo fmt -o align_entries=false,array_auto_collapse=false,reorder_keys=true,column_width=120`

**Review by nspin — APPROVED** [review]

**Comment by dominic-mulligan-arm** [comment]
+1+1+1+1 = +1 reached, merging.

**Pull request merged**
