### PR TITLE
Added Nitro build to CI workflow

### PR DESCRIPTION
**Pull request by dominic-mulligan-arm**
Added a new Nitro CI workflow which builds the `nitro` and `nitro-cli` targets for Veracruz.  Also expanded existing workflows to also cover their respective `*-cli` targets.

Due to us hitting disk-space constraints when building for TZ I've also removed some unnecessary pre-installed software from the Github runner:

- Android support libraries,
- The .NET runtime,
- The Glorious Glasgow Haskell Compiler 🥲
- The Boost C++ library.

This is done now as part of the initial SDK compilation step.  Further ideas for maximising disk space, should it be necessary, are available [here](https://github.com/easimon/maximize-build-space).

### CODE REVIEW

**Comment by dominic-mulligan-arm** [comment]
This is ready for review now: the Nitro workflow is succeeding, at least.

**Review by mathias-arm — DISMISSED** [review]

**Review by dreemkiller — APPROVED** [review]

**Review by ShaleXIONG — DISMISSED** [review]

**Comment by dominic-mulligan-arm** [comment]
Sorry @mathias-arm and @dreemkiller: it seems that the `tz` build target is running out of space during the build and aborting (but for some reason Github considers this a success, and will allow the merge).  I've extended the changeset to try to free up disk space before every build by removing redundant .Net, Haskell, and Android toolchains/libraries pre-installed on the Azure machines backing Github actions.

**Comment by dominic-mulligan-arm** [comment]
I'm leaving `trustzone-cli` build out of this change until I have time to come back and look at why it is consuming so much disk space.  I think getting Nitro builds in is more important, for the time being.  Can anybody take a look at this and approve/reject as appropriate?

**Comment by mathias-arm** [comment]
I do wonder if using LTO does not increase the size of the build directories.

**Review by mathias-arm — APPROVED** [review]

**Pull request merged**
