### PR TITLE
Add network documentation

### PR DESCRIPTION
**Pull request by gbryant-arm**
Document network stack.

TODO:
* Add doc for proxy attestation server

### CODE REVIEW

**Comment by dominic-mulligan-arm** [comment]
Are you adding the documentation for the PAS in this PR?

**Comment by gbryant-arm** [comment]
> Are you adding the documentation for the PAS in this PR?

Yes

**Comment by dominic-mulligan-arm** [comment]
Is this nearly ready for review?

**Comment by gbryant-arm** [comment]
I haven't written the doc for the PAS yet. I'm focusing on writing the ML native module

**Comment by dominic-mulligan-arm** [comment]
Can't you do both?  I'm a bit confused why you opened this, only to have it sit on the pull request list, if you're not going to be working on it.  Also, can you open a PR for the Tensorflow Native Module work?

**Comment by gbryant-arm** [comment]
> Can't you do both?

Yes I am working on it during builds.

It was sitting on my local machine for a month so from my perspective opening a PR is definitely an improvement. Isn't the point of WIP / draft PRs to give peers an early access preview of the changes? My intention was to give @geky, @dreemkiller or anyone else an opportunity to request changes before I go too far.
What's an acceptable PR age in your opinion? Some PRs have been open for months.

I'm opening a PR for the ML native module.

**Comment by dominic-mulligan-arm** [comment]
What's the status of this PR?

**Comment by gbryant-arm** [comment]
> What's the status of this PR?

I wrote the PAS doc, waiting for @dreemkiller 's input

**Review by dominic-mulligan-arm — APPROVED** [review]
Approved, but let's wait for @dreemkiller.

**Pull request merged**
