### PR TITLE
use the renamed version of the Nitro Enclave attestation crate

### PR DESCRIPTION
**Pull request by dreemkiller**
I've renamed the Nitro Enclave Attestation Token crate to nitro-enclave-attestation-document. This change uses that new repo and it's updated components.

### CODE REVIEW

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: a6f532fd4362605d2291aa1068cd48564262d185
* Result: SUCCEEDED
* [Build Logs](https://01evtei465.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=f791dff9-cd28-44e7-b9da-628702a61eba%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by ShaleXIONG — APPROVED** [review]

**Review by dominic-mulligan-arm — APPROVED** [review]

**Comment by dominic-mulligan-arm** [comment]
@dreemkiller does merging this need to be co-ordinated with merging another change, or can it be merged right away?

**Comment by dreemkiller** [comment]
It's not required, but I would prefer #180 go in first.

**Comment by dominic-mulligan-arm** [comment]
@dreemkiller, once CI completes I'll merge #201.  Can you rebase this immediately after and we can get it in?

**Comment by dominic-mulligan-arm** [comment]
Sorry, didn't realise how much your recent CI changes would speed up the CI.  OK, this is next if you can rebase.

**Comment by dreemkiller** [comment]
The CI changes should speed things up that much. It should now be ~2 hours. If it’s less than that, there’s a problem.

**Comment by dominic-mulligan-arm** [comment]
> The CI changes should speed things up that much. It should now be ~2 hours. If it’s less than that, there’s a problem. From: 

Yeah I've just checked the build logs being produced and there's a problem with the CI log reporting bot which is reporting CI success and leaving the PR in a mergeable state within 10 minutes.  Think I jumped the gun merging @SabreenKaur's changes (but they're documentation only, so shouldn't break `main`), ha!

**Review by dominic-mulligan-arm — APPROVED** [review]

**Pull request merged**
