### PR TITLE
Minor improvements to IceCap documentation

### PR DESCRIPTION
**Pull request by nspin**
Proudly remove "WIP" designation, and add an additional paragraph about running tests on the Raspberry Pi 4.

### CODE REVIEW

**Review by dominic-mulligan-arm — APPROVED** [review]

**Comment by dominic-mulligan-arm** [comment]
@nspin can you rewrite history to sign all of your commits?  Merging is blocked otherwise.

**Review by geky — DISMISSED** [review]
Looks good to me!

**Comment by nspin** [comment]
> @nspin can you rewrite history to sign all of your commits? Merging is blocked otherwise.

Oops, all done.

**Review by dominic-mulligan-arm — APPROVED** [review]

**Comment by dominic-mulligan-arm** [comment]
+1 reached, merging.

**Pull request merged**
