### PR TITLE
Rename Colima to TransportProtocol

### PR DESCRIPTION
**Pull request by gbryant-arm**
This PR aims at renaming Colima to TransportProtocol. Nothing else worth mentioning.

Ready for review

### CODE REVIEW

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: a4bfbacf3f8b698eb8b058685ec3f9c28f79bd67
* Result: SUCCEEDED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=35ffcf9a-d124-4243-a737-a007a4404830%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by dominic-mulligan-arm** [comment]
@gbryant-arm, please include a more descriptive summary of what this change does. Any comment like "ready for review" should be added in a comment in the thread of updates below the main description. Thanks!

**Review by ShaleXIONG — DISMISSED** [review]

**Comment by dominic-mulligan-arm** [comment]
We'll merge #92 and then this.  Can you rebase onto current main in preparation?

**Comment by gbryant-arm** [comment]
Rebased

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: b67a693f94df27e2798951cdfbcf16f24cb75e38
* Result: FAILED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=fd4c6dd1-3863-472b-a4e3-1daa8e6c3545%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by dominic-mulligan-arm — APPROVED** [review]

**Comment by dominic-mulligan-arm** [comment]
This can be merged if the build finishes successfully.

**Comment by veracruz-project-owner** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Veracruz
* Commit ID: 991429de0ef4947da70bf6b906e88384b7654253
* Result: SUCCEEDED
* [Build Logs](https://t4r5bdzqe9.execute-api.eu-west-2.amazonaws.com/Prod/buildlogs?key=be0cdf6a-7800-4536-bd12-830bf5029600%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by dominic-mulligan-arm** [comment]
+1 reached, merging.

**Pull request merged**
