### PR TITLE
Go

### PR DESCRIPTION
**Pull request by paul-111**

### CODE REVIEW

**Comment by AryanGodara** [comment]
@paul-111 are you by any chance using windows as the OS for cloning the project?
(I'm another outreachy applicant, so it's just a curious query)

**Comment by paul-111** [comment]
@AryanGodara hii yes i am using windows

**Comment by paul-111** [comment]
thank you @paul-111 , yes i tried it in the root directory and tried according to the instructions veracruz community gave me, now waiting for their reviews

**Comment by AryanGodara** [comment]
@paul-111 I will suggest that you should either dual boot ubuntu(linux)  or use a virtual machine for this project.
This is because most of the terminal guides are not written for windows. Also, many files (like the ones that you have accidentally "deleted" in your commit) have file names that are "invalid" in windows (but are valid in linux).
Another option is to use WSL2 (windows subsystem for linux) along with windows terminal. And the install ubuntu or debian from the windows store.
(The second step  is very complicated and tedious, so the easier path is to simply dual boot ubuntu)

**Comment by AryanGodara** [comment]
Also, the `certificate of origin` isn't supposed to be a .txt file in your commit; instead, paste that text inside the PR description (at the top of this page, where you describe your pull request).
Then, you can delete the `certificateoforigin.txt` file and also remove all the `deleted files` from your commit (You can do this using the command: `git RESTORE --staged <individual_file_name>`).
Only add the files in your commit that you made changes to yourself (not the ones automatically added by git, because you're using windows instead of linux)

Lastly, your commits need to be `verified`. Generate the `GPG key` for that following the steps provided in any of the previous PRs made by me, or the last PR you made(that is currently drafted)

**Comment by paul-111** [comment]
@AryanGodara okk i really haven't notice that invalid files, thank you for pointing it out, i am working on it now

**Comment by paul-111** [comment]
@AryanGodara hii would you plz take a look at this https://github.com/veracruz-project/veracruz/pull/405 and see whether its correct this time or not? Thank you

**Comment by AryanGodara** [comment]
> @AryanGodara hii would you plz take a look at this #405 and see whether its correct this time or not? Thank you

Your commit is still not verified. Are you having troubles with the GPG key generation and usage?
Also, please don't make new PRs everytime you make changes to the code. Instead, just push the changes to the same PR. 

Lastly, at the end, you'll have to remove all the `unverified commits` and commit one final time which is `verified` or else, it'll not be merged. 

As for the content, I think mentor Shale Xiong can guide you on that. I can see that you've written the steps to compile Golang to .wasm. But I think we had to upload .go files (not just txt) and we have to make use of the `veracruz freestanding-execution-engine` not wasmtime. So please clear that on Monday, when everyone is back for work.
(I don't know much tbh, since I'm also just an outreachy intern😅)

**Pull request closed without merging**
