### PR TITLE
WIP: adding Golang

### PR DESCRIPTION
**Pull request by paul-111**

### CODE REVIEW

**Comment by dominic-mulligan-arm** [comment]
Hi @paul-111!  Thanks for opening your first pull request, and welcome to the Veracruz project!   🎉

What are your plans with this pull request?  Do you intend to add some Go language translations of our existing examples, in `sdk/rust-examples`?  That would be very helpful, and a valuable contribution to the project, if so...

However, before any pull request can be merged, two issues need to be resolved:

# Developer Certificate of Origin

As this is your first commit to the Veracruz repository can you please certify that you have authorisation to contribute code using the Developer Certificate of Origin?  This is a requirement of the Veracruz organization, which we agreed with the Linux Foundation when we were adopted.  To do this, it's enough to include the following text in your PR message, at the top:

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

# Signed commits

Can I ask that you sign all of your commits using GPG?  We adopted this rule a while ago as a security/integrity mechanism and code cannot be merged into the main Veracruz repository without this signing.  If you don't know how to do this, then follow these instructions:

1. Generate a new GPG key: `gpg --gen-key` and follow the instructions asking for your name, email, etc.
2. List the GPG keys available: `gpg --list-secret-keys --keyid-format=long`.  Make a note of the ID of the key you’ve just generated (it’s a long string of capital letters and numbers),
3. Export the public key component of the generated key to stdout : `gpg --armor --export $KEYID` where `$KEYID` is the long string of letters and numbers, above.
4. Go to your Github profile’s settings page, go to the Keys section, add a new GPG key and copy-paste the public key printed out above.
5. Tell Git to use this key when signing commits: `git config --global user.signingkey $KEYID` , again where `$KEYID` is the long string of letters and numbers, above.
6. Tell Git to always sign your commits: `git config --global commit.gpgsign true` (Note, as an alternative, you can choose not to set this but then you will always need to commit using `git commit -S`)
7. To test if your commits are being signed correctly, commit something on a local copy, and then use: `git log --show-signature`.  Note that Github signs their own merge commits made to a repository when a pull request is merged, but the command above may not show the signed commits correctly (they’ll be highlighted in red) as you need to import Github’s public key to verify the signature.  To do this, import Github’s key by: `curl https://github.com/web-flow.gpg | gpg --import` Showing the signatures in Git log should now work, and Git should recognise that Github’s merge commits were signed by Github (they should now be blue).

Once you've setup GPG signing, you usually have to `export GPG_TTY=$(tty)` in your terminal (or you'll get an error about a missing `tty`) prior to commiting/rebasing.  Once that is done, edit your PR to sign all commits and push again.

**Comment by paul-111** [comment]
Hii @dominic-mulligan-arm i am working as an outreachy applicant under mentor Shale Xiong where he gave me task regarding "Instructions for compiling Golang into WASM and running it using Wasmtime ", the fact that i am working under outreachy program do i still need this Developer certificate of origin and Signed commits issues to solve ? Thank you

**Comment by dominic-mulligan-arm** [comment]
Hi @paul-111, OK great, thanks for that information---I know @ShaleXIONG has been very busy recently co-ordinating with different prospective candidates from Outreachy.  I think what would make your PR especially valuable is not just information on how to compile Go programs for Wasm, but also to try to translate some of our existing examples to Go, in addition to the instructions, as I mentioned.  Can you try and translate, e.g., one or two of the Rust examples into Go, and add them to this PR?

(Further, just echoing @dreemkiller): yes as a prospective Outreachy intern you need to include the Developer Certificate of Origin in your commit message, as it means we then know that the work is yours, and you have permission to submit it to Veracruz.  Also, every commit that goes into our repository must be signed by its owner: Github will simply not allow us to merge your PR without that signing.  This is a security/integrity mechanism and unfortunately cannot be over-ridden, even if it is a bit of a pain for new users 😀

**Comment by ShaleXIONG** [comment]
Hi @paul-111 If you have questions on the merge request, we can have a video chat and you can share your screen so we sort out the problem together. You can directly find/ping me in the slack or email me.

I also remember you had the problem of clone the repo; however it looks like you sort it out.

**Comment by dominic-mulligan-arm** [comment]
@paul-111 is this PR being worked on, still?

**Comment by paul-111** [comment]
@dominic-mulligan-arm  hii yes, this PR needs some modification and i am working on it and i might be able to update it by 2/3 days

**Comment by dominic-mulligan-arm** [comment]
Great, thanks @paul-111.  In the meantime, I will convert it into a draft until it is ready for review.

**Comment by paul-111** [comment]
@dominic-mulligan-arm  hii regarding this gpg key , would you plz tell me is there any specific directory under which i have to create it or just simply under veracruz?

**Comment by AryanGodara** [comment]
> @dominic-mulligan-arm hii regarding this gpg key , would you plz tell me is there any specific directory under which i have to create it or just simply under veracruz?

You can do it from the project root directory (/veracruz) to be safe. But it should also work from any other directory (I tried it both ways). The GPG key is not specific to a single repository.
```
https://docs.github.com/en/enterprise-server@3.1/authentication/managing-commit-signature-verification/generating-a-new-gpg-key
```
You can follow the steps on this page if it helps!

**Pull request closed without merging**
