### PR TITLE
Switch to Veracruz fork of pinecone.

### PR DESCRIPTION
**Pull request by egrimley-arm**

### CODE REVIEW

**Comment by dominic-mulligan-arm** [comment]
Is this ready for review or still a WIP?

**Comment by egrimley-arm** [comment]
> Is this ready for review or still a WIP?

It's ready for review, I think, but there are sort of "strategic" questions about whether this is the right direction and whether we want to get there with lots of little steps or one huge change. Mathias didn't seem totally opposed to this move, but perhaps we should get his approval.

**Comment by mathias-arm** [comment]
For this PR, I have a strong suspicion the branch needs to be added. We don't want to rely on what the repository default branch is (currently it is `main` which is the same as upstream).

The "strategic" question is whether it would be easier to switch to `postcard` directly, or use this as an intermediate step.

**Comment by dominic-mulligan-arm** [comment]
@mathias-arm let's bite the bullet, get this in, and then discuss whether we want to move to `postcard` after this has been merged.

**Review by dominic-mulligan-arm — APPROVED** [review]

**Comment by dominic-mulligan-arm** [comment]
LGTM.  Though @egrimley-arm can you open a PR with a description of why the PR is being opened in future?  It's hard to keep track of why certain changes are being made, and having some textual recording of why things were done is useful.

**Pull request merged**
