### PR TITLE
No change.

### PR DESCRIPTION
**Pull request by egrimley-arm**

### CODE REVIEW

**Comment by nspin** [comment]
What is the purpose of this PR?

**Comment by egrimley-arm** [comment]
> What is the purpose of this PR?

Just checking that `main` isn't broken for some reason.

**Comment by dominic-mulligan-arm** [comment]
Doesn't the build badge in the `README` for the repository do that, though?

**Comment by egrimley-arm** [comment]
> Doesn't the build badge in the `README` for the repository do that, though?

I don't know. The GitHub CI is generally very confusing. Where is the list of all recent CI runs, for example, together with a clear indication of exactly which commit was being tested and at what time?

**Pull request closed without merging**
