### PR TITLE
One bug fix for issue #565.

### PR DESCRIPTION
**Pull request by egrimley-arm**
* In io-utils, use write_all/read_exact instead of write/read.

### CODE REVIEW

**Comment by egrimley-arm** [comment]
@gbryant-arm Can this be merged now?

**Review by gbryant-arm — CHANGES_REQUESTED** [review]
The broken pipe bug on Linux is fixed by remapping `stdout` to `/dev/null`. Would that be easier for VC-Server and RM to use a channel other than `stdout` for syncing, say a named pipe? This way we wouldn't interfere with the standard channels, which will make it easier in the future to redirect them to `/dev/null` depending on whether we are in debug mode

**Comment by egrimley-arm** [comment]
It would almost certainly not be "easier" ... and I don't know exactly what's possible on Nitro, but presumably the enclave is not sharing a file system with the host? Shall I just remove the `/dev/null` part of this PR so we can merge the rest and close this PR?

**Comment by egrimley-arm** [comment]
Perhaps the correct solution is to have the runtime manager connect to the Veracruz server rather than the other way round? Or is that not allowed? This PR is probably not the right place to discuss!

**Comment by egrimley-arm** [comment]
I've removed the `/dev/null` stuff.

**Comment by gbryant-arm** [comment]
> I've removed the `/dev/null` stuff.

Sounds good. I'm updating issue #565 to reflect that

**Pull request merged**
